# Generated by Django 3.2.6 on 2021-10-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icons',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
