# Generated by Django 3.2.6 on 2021-11-01 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0005_category_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='property_author', to='auth.user'),
            preserve_default=False,
        ),
    ]
